site_name: XSeeker documentation
repo_url: https://unh-pfem-gitlab.ara.inrae.fr/chopin/xseeker
repo_name: chopin/xseeker
theme:
  name: material
  logo: https://avatars.githubusercontent.com/u/17082156?s=200&v=4
  favicon: https://avatars.githubusercontent.com/u/17082156?s=200&v=4
  features:
    - content.code.copy
    - content.code.select
    #- content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.path
    - toc.integrate
  icon:
    repo: fontawesome/brands/gitlab
nav:
  - Introduction: index.md
  - For developpers:
    - Introduction: for_dev/index.md
    - Installation of XSeekerBaseModule: for_dev/xseekerbasemodule.md
    - Installation of XSeeker: for_dev/xseeker.md
  - On Galaxy W4M:
    - Introduction: on_galaxy/index.md
    - XSeeker Preparator: on_galaxy/xseeker_preparator.md
    - XSeeker tool: on_galaxy/xseeker_tool.md
  - How to use XSeeker ?:
    - Introduction: how_to_use/index.md
    - KMD plot: how_to_use/kmd_plot.md
    - Chromatogram and mass spectrum: how_to_use/chromato.md
    - Cluster table: how_to_use/cluster_table.md
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.pathconverter
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - git-authors

